apiVersion: v1
kind: Service
metadata:
  labels:
    app: varmor
  name: varmor-classifier-svc
  namespace: varmor
spec:
  ports:
  - port: 5000
    name: class
    targetPort: 5000
  selector:
    app: varmor
    app.kubernetes.io/name: varmor-classifier
