apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: varmor-agent
  namespace: varmor
  labels:
    app: varmor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: varmor-agent
subjects:
- kind: ServiceAccount
  name: varmor-agent
  namespace: varmor
