apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: varmor-agent
  labels:
    app: varmor
rules:
- apiGroups:
  - crd.varmor.org
  resources:
  - armorprofiles
  verbs:
  - get
  - list
  - watch
