apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: varmor-manager
  labels:
    app: varmor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: varmor-manager
subjects:
- kind: ServiceAccount
  name: varmor-manager
  namespace: varmor
