apiVersion: crd.varmor.org/v1beta1
kind: VarmorPolicy
metadata:
  name: varmorpolicy-sample
  namespace: nginx
spec:
  target:
    kind: Deployment
    name: nginx-deployment
    selector:
      matchLabels:
        app: nginx
  policy:
    mode: CustomPolicy
    customPolicy:
      network:
        matchProtocols:
        - protocol: icmp
      process:
        matchPaths:
        - path: /bin/su
          fromSource:
          - path: /bin/bash
          - path: /bin/sh
      file:
        matchPaths:
        - path: /etc/shadow
        matchDirectories:
        - dir: /run/secrets/kubernetes.io/serviceaccount/
          recursive: true
          fromSource:
          - path: /bin/bash
          - path: /bin/sh
      action:
        Block
