apiVersion: crd.varmor.org/v1beta1
kind: VarmorPolicy
metadata:
  name: varmorpolicy-sample
  namespace: nginx
spec:
  target:
    kind: Deployment
    name: nginx-deployment
    selector:
      matchLabels:
        app: nginx
  policy:
    mode: AlwaysAllow
