{{- if .Values.image.password }}
apiVersion: v1
kind: Secret
metadata:
  name: varmor-image-pull-secret
  namespace: {{ include "varmor.namespace" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "imagePullSecret" . }}
{{- end }}
