apiVersion: v1
kind: Service
metadata:
  name: varmor-status-svc
  namespace: {{ include "varmor.namespace" . }}
  labels:
    {{- include "varmor.manager.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: status
    targetPort: 8080
  selector:
    {{- include "varmor.manager.selectorLabels" . | nindent 4 }}
    identity: leader
