apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: varmor-agent
  namespace: {{ include "varmor.namespace" . }}
  labels:
    {{- include "varmor.agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: varmor-agent
subjects:
- kind: ServiceAccount
  name: varmor-agent
  namespace: {{ include "varmor.namespace" . }}
