{{- if .Values.agent.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: varmor-agent
  namespace: {{ include "varmor.namespace" . }}
  labels:
    {{- include "varmor.agent.labels" . | nindent 4 }}
{{- end }}
