apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "varmor.agent.fullname" . }}
  namespace: {{ include "varmor.namespace" . }}
  labels:
    {{- include "varmor.agent.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
