apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "varmor.agent.fullname" . }}
  labels:
    {{- include "varmor.agent.labels" . | nindent 4 }}
rules:
- apiGroups:
  - crd.varmor.org
  resources:
  - armorprofiles
  verbs:
  - get
  - list
  - watch
