{{- if .Values.manager.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "varmor.manager.serviceAccountName" . }}
  namespace: {{ include "varmor.namespace" . }}
  labels:
    {{- include "varmor.manager.labels" . | nindent 4 }}
{{- end }}
